// site/src/components/SearchInput.vue
<template>
  <div
    ref="searchForm"
    class="searchFormDiv"
    v-click-outside="onBlur"
    :class="{ 'input-focus': data.inputFocus, 'show-histories': showHistories }"
  >
    <form action="/search" method="GET" class="search-input">
      <input
        v-model="data.keyword"
        name="q"
        class="input"
        type="text"
        maxlength="30"
        :placeholder="$t('component.searchInput.placeholder')"
        autocomplete="off"
        aria-autocomplete="off"
        @focus="onFocus"
        @input="onInput"
        @keyup.down="changeSelect(1)"
        @keyup.up="changeSelect(-1)"
        @keyup.enter="searchBoxOnEnter"
      />
      <span @click="submitSearch">
        <i class="iconfont icon-search" />
      </span>
    </form>
    <div class="histories">
      <ul>
        <li
          v-for="(item, index) in histories"
          :key="index"
          :class="{ selected: index === data.selectedIndex }"
          @mouseover="historyItemMouseOver(index)"
          @mouseout="historyItemMouseOut()"
        >
          <span @click="historyItemClick(item)">{{ item }}</span>
          <i class="iconfont icon-close" @click="deleteHistory(item)" />
        </li>
      </ul>
    </div>
  </div>
</template>

<script setup>
const localStorageKey = "bbsgo.search.histories";
const maxHistoryLen = 10;
const route = useRoute();

const data = reactive({
  keyword: route.query.q || "",
  inputFocus: false,
  selectedIndex: -1,
  allHistories: [],
});

const showHistories = computed(() => {
  return (
    data.inputFocus && histories && histories.value && histories.value.length
  );
});

const histories = computed(() => {
  if (data.keyword) {
    return data.allHistories.filter((history) => {
      return history.includes(data.keyword);
    });
  }
  return data.allHistories;
});

onMounted(() => {
  loadAllHistories();
});

const searchBoxOnEnter = (e) => {
  e.stopPropagation();

  // 如果选中了历史搜索记录，那么使用历史搜索记录
  if (
    data.selectedIndex >= 0 &&
    histories.value &&
    histories.value.length > data.selectedIndex
  ) {
    data.keyword = histories.value[data.selectedIndex];
  }
  submitSearch();
};
const historyItemClick = (keyword) => {
  data.keyword = keyword;
  submitSearch();
};
const submitSearch = () => {
  if (!data.keyword) {
    return;
  }
  addHistories();
  window.location = "/search?q=" + encodeURIComponent(data.keyword);
};
const onFocus = () => {
  data.inputFocus = true;
};
const onBlur = () => {
  data.inputFocus = false;
};
const onInput = () => {
  data.selectedIndex = -1;
};
const changeSelect = (delta) => {
  if (!histories.value || !histories.value.length) {
    return;
  }
  let index = data.selectedIndex + delta;
  if (index < 0) {
    // 选中熬第一个了，再往上取消选中
    index = -1;
  } else if (index >= histories.value.length) {
    // 选中到最后了，再往下就回到第一个
    index = 0;
  }
  data.selectedIndex = index;
};
const historyItemMouseOver = (index) => {
  data.selectedIndex = index;
};
const historyItemMouseOut = () => {
  data.selectedIndex = -1;
};
const loadAllHistories = () => {
  try {
    data.allHistories = JSON.parse(localStorage.getItem(localStorageKey)) || [];
  } catch (error) {
    data.allHistories = [];
  }
};
const addHistories = () => {
  if (!data.keyword) {
    return;
  }
  const newArray = [];
  newArray.push(data.keyword);
  if (data.allHistories && data.allHistories.length) {
    for (let i = 0; i < data.allHistories.length; i++) {
      const element = data.allHistories[i];
      if (newArray.length < maxHistoryLen && !newArray.includes(element)) {
        newArray.push(element);
      }
    }
  }
  localStorage.setItem(localStorageKey, JSON.stringify(newArray));
  data.allHistories = newArray;
};
const deleteHistory = (kw) => {
  const newArray = [];
  if (data.allHistories && data.allHistories.length) {
    for (let i = 0; i < data.allHistories.length; i++) {
      const element = data.allHistories[i];
      if (element !== kw && !newArray.includes(element)) {
        newArray.push(element);
      }
    }
  }
  localStorage.setItem(localStorageKey, JSON.stringify(newArray));
  data.allHistories = newArray;
};
</script>

<style lang="scss" scoped>
.searchFormDiv {
  @media screen and (max-width: 768px) {
    & {
      display: none;
    }
  }

  $search-box-width: 280px;
  $search-box-unfocus-width: 180px;
  $focus-color: #0065ff; // TODO

  &.input-focus {
    .search-input {
      background-color: var(--bg-color);
      border: 1px solid var(--border-color3);
    }
    .icon-search {
      color: $focus-color;
    }
  }

  &.show-histories {
    .histories {
      display: block;
    }
  }

  .search-input {
    width: $search-box-unfocus-width;
    background-color: var(--bg-color2);
    border: 1px solid var(--border-color);
    height: 34px;
    border-radius: 17px;
    padding: 4px 10px;
    font-size: 14px;
    display: flex;
    transition-property: background-color, border, color;
    transition-duration: 0.25s;
    transition-timing-function: ease-in;
    transition: width 0.5s;

    &:has(.input:focus) {
      width: $search-box-width;
      border: 1px solid $focus-color;
    }

    input {
      color: var(--text-color);
      font-weight: 400;
      font-size: 13px;
      height: 100%;
      width: 100%;
      flex: 1 1;
      padding: 0;
      margin: 0 5px;
      overflow: hidden;
      background: transparent;
      border: none;
      resize: none;
      box-shadow: none;

      &:focus {
        outline: none;
      }
    }
  }

  span {
    padding: 0 4px 0 10px;
    cursor: pointer;
  }

  .histories {
    width: $search-box-width;
    display: none;
    height: auto;
    top: 48px;
    position: fixed;

    background-color: var(--bg-color);
    border: 1px solid var(--border-color);
    border-radius: 4px;
    box-shadow: 0 5px 20px rgb(18 18 18 / 10%);
    z-index: 203;

    animation: showHistoriesAnimation 0.3s;
    -moz-animation: showHistoriesAnimation 0.3s; /* Firefox */
    -webkit-animation: showHistoriesAnimation 0.3s; /* Safari and Chrome */
    -o-animation: showHistoriesAnimation 0.3s; /* Opera */

    @keyframes showHistoriesAnimation {
      0% {
        opacity: 0;
        transform: translate(1px, 30px);
      }
      100% {
        opacity: 1;
        transform: translate(0, 0);
      }
    }
    ul {
      li {
        padding: 7px 16px;
        width: 100%;
        text-align: left;
        cursor: pointer;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;

        display: flex;
        span {
          width: 100%;
          font-size: 13px;
          font-weight: 400;
          color: var(--text-color);
        }
        &:hover {
          i.iconfont {
            display: block;
          }
        }
        i.iconfont {
          display: none;
          font-size: 13px;
          padding: 0 6px;
          &:hover {
            color: #4e6ef2;
          }
        }
        &.selected {
          background-color: var(--bg-color2);
        }
      }
    }
  }
}
</style>

// web/components/common/search-input.tsx
"use client"

import * as React from "react"
import { Clock, Search, X } from "lucide-react"
import { useSearchParams } from "@/lib/router/navigation"

import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"

const localStorageKey = "bbsgo.search.histories"
const maxHistoryLen = 10

export function SearchInput({
  className,
  placeholder = "",
}: {
  className?: string
  placeholder?: string
}) {
  return (
    <React.Suspense
      fallback={
        <Input
          className={cn("h-9 rounded-lg", className)}
          placeholder={placeholder}
          disabled
        />
      }
    >
      <SearchInputContent className={className} placeholder={placeholder} />
    </React.Suspense>
  )
}

function SearchInputContent({
  className,
  placeholder = "",
}: {
  className?: string
  placeholder?: string
}) {
  const searchParams = useSearchParams()
  const [keyword, setKeyword] = React.useState(searchParams.get("q") || "")
  const [inputFocus, setInputFocus] = React.useState(false)
  const [selectedIndex, setSelectedIndex] = React.useState(-1)
  const [allHistories, setAllHistories] = React.useState<string[]>(() => {
    if (typeof window === "undefined") return []
    try {
      const parsed = JSON.parse(localStorage.getItem(localStorageKey) || "[]")
      return Array.isArray(parsed) ? parsed : []
    } catch {
      return []
    }
  })

  const histories = React.useMemo(() => {
    if (!keyword) return allHistories
    return allHistories.filter((history) => history.includes(keyword))
  }, [allHistories, keyword])

  const showHistories = inputFocus && histories.length > 0

  function addHistories(query: string) {
    const next = [
      query,
      ...allHistories.filter((item) => item !== query),
    ].slice(0, maxHistoryLen)
    localStorage.setItem(localStorageKey, JSON.stringify(next))
    setAllHistories(next)
  }

  function submitSearch(query = keyword) {
    const next = query.trim()
    if (!next) return
    addHistories(next)
    window.location.assign(`/search?q=${encodeURIComponent(next)}`)
  }

  function onSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault()
    submitSearch()
  }

  function changeSelect(delta: number) {
    if (!histories.length) return
    setSelectedIndex((current) => {
      const next = current + delta
      if (next < 0) return -1
      if (next >= histories.length) return 0
      return next
    })
  }

  function onKeyDown(event: React.KeyboardEvent<HTMLInputElement>) {
    if (event.key === "ArrowDown") {
      event.preventDefault()
      changeSelect(1)
      return
    }
    if (event.key === "ArrowUp") {
      event.preventDefault()
      changeSelect(-1)
      return
    }
    if (event.key === "Enter") {
      event.stopPropagation()
      event.preventDefault()
      if (selectedIndex >= 0 && histories[selectedIndex]) {
        setKeyword(histories[selectedIndex])
        submitSearch(histories[selectedIndex])
        return
      }
      submitSearch()
    }
  }

  function deleteHistory(item: string) {
    const next = allHistories.filter((history) => history !== item)
    localStorage.setItem(localStorageKey, JSON.stringify(next))
    setAllHistories(next)
  }

  function historyItemClick(item: string) {
    setKeyword(item)
    submitSearch(item)
  }

  return (
    <div className={cn("relative", className)}>
      <form
        action="/search"
        method="GET"
        onSubmit={onSubmit}
        className={cn(
          "flex h-8 w-48 items-center gap-1 rounded-sm border border-border bg-muted px-3 py-1 text-sm transition-all duration-300 ease-in-out focus-within:w-72 focus-within:border-ring focus-within:bg-background focus-within:shadow-sm focus-within:shadow-ring/20",
          inputFocus &&
            "w-72 border-ring bg-background shadow-sm shadow-ring/20"
        )}
      >
        <Input
          type="text"
          name="q"
          value={keyword}
          maxLength={30}
          autoComplete="off"
          onFocus={() => setInputFocus(true)}
          onBlur={() => window.setTimeout(() => setInputFocus(false), 200)}
          onChange={(event) => {
            setKeyword(event.target.value)
            setSelectedIndex(-1)
          }}
          onKeyDown={onKeyDown}
          placeholder={placeholder}
          className="h-9 flex-1 border-none bg-transparent p-0 text-xs shadow-none focus-visible:ring-0 focus-visible:ring-offset-0"
        />
        <Button
          type="button"
          variant="ghost"
          size="sm"
          className={cn(
            "h-auto p-1 text-muted-foreground hover:bg-transparent hover:text-foreground",
            inputFocus && "text-primary"
          )}
          onClick={() => submitSearch()}
        >
          <Search className="h-4 w-4" />
        </Button>
      </form>

      {showHistories ? (
        <div className="absolute top-full left-0 z-50 mt-1 w-72 animate-in duration-200 slide-in-from-top-2">
          <div className="overflow-hidden rounded-lg border border-border bg-popover shadow-lg">
            {histories.map((item, index) => (
              <div
                key={item}
                className={cn(
                  "group flex cursor-pointer items-center justify-between border-b border-border px-3 py-2 transition-colors last:border-b-0 hover:bg-accent",
                  index === selectedIndex && "bg-accent"
                )}
                onMouseOver={() => setSelectedIndex(index)}
                onMouseOut={() => setSelectedIndex(-1)}
              >
                <button
                  type="button"
                  className="flex flex-1 cursor-pointer items-center text-left text-xs text-foreground"
                  onClick={() => historyItemClick(item)}
                >
                  <Clock className="mr-2 h-3 w-3 opacity-50" />
                  {item}
                </button>
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  className="h-auto bg-transparent p-1 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100 hover:bg-transparent hover:text-destructive"
                  onClick={() => deleteHistory(item)}
                >
                  <X className="h-3 w-3" />
                </Button>
              </div>
            ))}
          </div>
        </div>
      ) : null}
    </div>
  )
}
