// site/src/components/ArticleList.vue
<template>
  <div v-for="article in articles" :key="article.id" class="article-item">
    <div class="article-item-main">
      <div class="article-info">
        <nuxt-link
          class="article-title"
          :to="'/article/' + article.id"
          target="_blank"
          >{{ article.title }}</nuxt-link
        >

        <div class="article-summary">
          {{ article.summary }}
        </div>
      </div>

      <div class="article-meta">
        <div class="article-meta-left">
          <span class="article-meta-item">
            <nuxt-link :to="'/user/' + article.user.id" class="article-author">
              <span>{{ article.user.nickname }}</span>
            </nuxt-link>
            <time :datetime="useFormatDate(article.createTime)"
              >{{ $t("component.articleList.publishedAt") }}
              {{ usePrettyDate(article.createTime) }}</time
            >
          </span>
        </div>

        <div class="article-meta-right">
          <div v-if="article.tags && article.tags.length > 0">
            <nuxt-link
              v-for="tag in article.tags"
              :key="tag.id"
              class="article-tag"
              :to="'/articles/tag/' + tag.id"
              >{{ tag.name }}</nuxt-link
            >
          </div>
        </div>
      </div>
    </div>
    <div v-if="article.cover" class="article-item-cover">
      <img :src="article.cover.url" />
    </div>
  </div>
</template>

<script setup>
const props = defineProps({
  articles: {
    type: Array,
    default() {
      return [];
    },
    required: false,
  },
});
</script>

<style lang="scss" scoped>
.article-item {
  padding: 12px 12px;
  transition: background 0.5s;
  border-radius: 3px;
  // background: var(--bg-color);
  line-height: 24px;

  &:not(:last-child) {
    margin-bottom: 10px;
  }

  display: flex;
  align-items: center;

  .article-item-main {
    width: 100%;
    display: flex;
    flex-direction: column;
    justify-content: space-between;

    .article-info {
      .article-title {
        font-size: 18px;
        line-height: 30px;
        font-weight: 500;
        color: var(--text-color);
        overflow: hidden;
        text-overflow: ellipsis;
      }

      .article-summary {
        font-size: 14px;
        color: var(--text-color2);
        overflow: hidden;
        display: -webkit-box;
        -webkit-box-orient: vertical;
        -webkit-line-clamp: 3;
        text-align: justify;
        padding-top: 6px;
        word-break: break-all;
        text-overflow: ellipsis;
      }
    }

    .article-meta {
      display: flex;
      // justify-content: space-between;
      align-items: center;
      font-size: 13px;
      padding-top: 6px;

      .article-meta-left {
        .article-meta-item {
          padding: 0 6px 0 0;
          color: var(--text-color3);

          .article-author {
            font-weight: bold;
            padding: 0 3px;
          }
        }
      }

      .article-meta-right {
        margin-left: 10px;

        @media screen and (max-width: 768px) {
          & {
            display: none;
          }
        }

        .article-tag {
          padding: 2px 8px;
          justify-content: center;
          align-items: center;
          border-radius: 12.5px;
          margin-right: 10px;
          background: var(--bg-color2);
          border: 1px solid var(--border-color2);
          color: var(--text-color3);
          font-size: 12px;

          &:hover {
            color: var(--text-link-color);
            background: var(--bg-color);
          }
        }
      }
    }
  }

  .article-item-cover {
    display: flex;
    margin-left: 6px;
    img {
      min-width: 140px;
      min-height: 90px;
      width: 140px;
      height: 90px;
      object-fit: cover;

      @media screen and (max-width: 768px) {
        & {
          min-width: 110px;
          min-height: 80px;
          width: 110px;
          height: 80px;
        }
      }
    }
  }
}
</style>

// web/components/article/article-list.tsx
import Link from "@/components/common/link"
import { UserAvatar } from "@/components/common/avatar"

import { EmptyState } from "@/components/common/empty-state"
import type { Article } from "@/lib/api/types"
import { prettyDate } from "@/lib/format"
import type { TFunction } from "@/lib/i18n"
import { EyeIcon, HeartIcon, MessageCircleIcon } from "lucide-react"

export function ArticleList({
  articles,
  t,
}: {
  articles: Article[]
  t: TFunction
}) {
  if (!articles.length) {
    return <EmptyState title={t("common.noData")} />
  }

  return (
    <div className="overflow-hidden rounded-lg bg-background">
      {articles.map((article) => (
        <ArticleListItem key={article.id} article={article} t={t} />
      ))}
    </div>
  )
}

function ArticleListItem({ article, t }: { article: Article; t: TFunction }) {
  const authorName =
    article.user.nickname || article.user.username || `#${article.user.id}`
  const articleUrl = `/article/${article.id}`

  return (
    <article className="group border-b border-border/70 bg-background px-3 py-4 transition-colors last:border-b-0 hover:bg-muted/35 sm:px-4 sm:py-5">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start">
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2.5 text-sm text-muted-foreground">
            <UserAvatar user={article.user} size={28} />
            <Link
              href={`/user/${article.user.id}`}
              className="min-w-0 truncate font-medium text-foreground/80 hover:text-primary"
            >
              {authorName}
            </Link>
            {article.createTime ? (
              <>
                <span className="h-1 w-1 shrink-0 rounded-full bg-muted-foreground/40" />
                <time
                  dateTime={new Date(article.createTime).toISOString()}
                  className="shrink-0"
                >
                  <span className="sr-only">
                    {t("component.articleList.publishedAt")}{" "}
                  </span>
                  {prettyDate(article.createTime, t)}
                </time>
              </>
            ) : null}
          </div>

          <Link
            href={articleUrl}
            target="_blank"
            className="mt-3 block text-[19px] leading-7 font-semibold text-balance text-foreground transition-colors group-hover:text-primary"
          >
            {article.title}
          </Link>

          {article.summary ? (
            <p className="mt-2 line-clamp-2 text-[15px] leading-7 break-words text-muted-foreground">
              {article.summary}
            </p>
          ) : null}

          <ArticleListMeta article={article} className="mt-4 hidden sm:flex" />
        </div>

        {article.cover?.url ? (
          <Link
            href={articleUrl}
            target="_blank"
            className="block overflow-hidden rounded-md bg-muted sm:w-40 md:w-44"
            aria-label={article.title}
          >
            <img
              src={article.cover.preview || article.cover.url}
              alt={article.title}
              className="aspect-[16/10] w-full object-cover transition-transform duration-300 group-hover:scale-[1.03] sm:aspect-[4/3]"
            />
          </Link>
        ) : null}

        <ArticleListMeta article={article} className="sm:hidden" />
      </div>
    </article>
  )
}

function ArticleListMeta({
  article,
  className = "",
}: {
  article: Article
  className?: string
}) {
  return (
    <div
      className={`flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-muted-foreground ${className}`}
    >
      <ArticleMetric icon={EyeIcon} value={article.viewCount} />
      <ArticleMetric
        icon={MessageCircleIcon}
        value={article.commentCount ?? 0}
        alwaysShow
      />
      <ArticleMetric icon={HeartIcon} value={article.likeCount} />
      {article.tags?.length ? (
        <div className="flex min-w-0 flex-wrap items-center gap-2">
          {article.tags.map((tag) => (
            <Link
              key={tag.id}
              href={`/articles/tag/${tag.id}`}
              className="rounded-full bg-muted px-2.5 py-1 text-xs leading-none text-muted-foreground transition-colors hover:bg-primary/10 hover:text-primary"
            >
              {tag.name}
            </Link>
          ))}
        </div>
      ) : null}
    </div>
  )
}

function ArticleMetric({
  icon: Icon,
  value,
  alwaysShow = false,
}: {
  icon: typeof EyeIcon
  value?: number
  alwaysShow?: boolean
}) {
  if (!alwaysShow && !value) {
    return null
  }

  const displayValue = value ?? 0

  return (
    <span className="inline-flex items-center gap-1.5">
      <Icon className="size-3.5" />
      <span>{formatCount(displayValue)}</span>
    </span>
  )
}

function formatCount(value: number) {
  if (value >= 10000) {
    return `${Number((value / 10000).toFixed(1))}w`
  }
  if (value >= 1000) {
    return `${Number((value / 1000).toFixed(1))}k`
  }
  return String(value)
}
