// web/app/routes/redirect.tsx
import { useSearchParams } from "react-router"

import { ErrorPage } from "@/components/common/error-page"
import { useI18n } from "@/lib/i18n/provider"
import { noindexRouteMeta } from "@/lib/seo"

export function meta({
  matches,
}: {
  matches: Array<{ data?: unknown; loaderData?: unknown }>
}) {
  return noindexRouteMeta(matches, "Redirect", "跳转")
}

export default function RedirectRoute() {
  const [searchParams] = useSearchParams()
  const url = searchParams.get("url") || ""
  const { t } = useI18n()
  if (
    !url.toLowerCase().startsWith("http://") &&
    !url.toLowerCase().startsWith("https://")
  ) {
    return <ErrorPage message={t("pages.redirect.error")} />
  }
  return (
    <section className="main">
      <div className="container">
        <div className="main-body redirect py-[100px] text-center">
          <a href={url} rel="nofollow">
            {t("pages.redirect.link")}
          </a>
        </div>
      </div>
    </section>
  )
}

// site/pages/redirect.vue
<template>
  <section class="main">
    <div class="container">
      <div class="main-body redirect">
        <div>
          <img src="~/assets/images/logo.png" style="max-width: 100px" />
        </div>
        <div style="margin: 20px 0">
          <a :href="url" rel="nofollow"
            >即将跳往站外地址，点击该链接继续跳转&nbsp;&gt;&gt;</a
          >
        </div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  asyncData({ query, error }) {
    const url = query.url
    if (!url) {
      error({
        statusCode: 500,
        message: '你访问的页面发生错误!',
      })
      return
    }
    const temp = url.toLowerCase()
    if (!temp.startsWith('http://') && !temp.startsWith('https://')) {
      error({
        statusCode: 500,
        message: '你访问的页面发生错误!',
      })
      return
    }
    return {
      url,
    }
  },
}
</script>

<style lang="scss" scoped>
.redirect {
  text-align: center;
  vertical-align: center;
  padding: 100px 0;
}
</style>
