// web/components/comment/text-editor.tsx
"use client"

import * as React from "react"
import { Image as ImageIcon, Plus, X } from "lucide-react"

import { PreviewableImage } from "@/components/common/image-preview"
import { Button } from "@/components/ui/button"
import { apiFetch } from "@/lib/api/client"
import type { ImageInfo } from "@/lib/api/types"
import { useI18n } from "@/lib/i18n/provider"
import { useToastActions } from "@/lib/toast"
import { cn } from "@/lib/utils"

export type TextEditorRef = {
  focus: () => void
  reset: () => void
}

async function uploadImage(file: File) {
  const body = new FormData()
  body.append("image", file, file.name)
  return apiFetch<{ url: string }>("/api/upload", { method: "POST", body })
}

const COMMENT_IMAGE_LIMIT = 9

function imageSrc(image: ImageInfo) {
  return image.url || image.preview || ""
}

export const TextEditor = React.forwardRef<
  TextEditorRef,
  {
    content: string
    imageList: ImageInfo[]
    height?: number
    focusHeight?: number
    disabled?: boolean
    onContentChange: (content: string) => void
    onImageListChange: (imageList: ImageInfo[]) => void
    onSubmit: () => void
  }
>(function TextEditor(
  {
    content,
    imageList,
    height = 80,
    focusHeight = 0,
    disabled,
    onContentChange,
    onImageListChange,
    onSubmit,
  },
  ref
) {
  const { t } = useI18n()
  const { catchError, msgWarning } = useToastActions()
  const wrapperRef = React.useRef<HTMLDivElement>(null)
  const textareaRef = React.useRef<HTMLTextAreaElement>(null)
  const fileInputRef = React.useRef<HTMLInputElement>(null)
  const isOpeningImagePickerRef = React.useRef(false)
  const unlockImagePickerTimerRef = React.useRef<number | null>(null)
  const [isFocus, setIsFocus] = React.useState(false)
  const [showImageUpload, setShowImageUpload] = React.useState(false)
  const [imageUploading, setImageUploading] = React.useState(false)
  const currentImages = imageList || []
  const canAddImage = currentImages.length < COMMENT_IMAGE_LIMIT

  React.useImperativeHandle(ref, () => ({
    focus() {
      textareaRef.current?.focus()
    },
    reset() {
      setIsFocus(false)
      setShowImageUpload(false)
    },
  }))

  React.useEffect(() => {
    return () => {
      if (unlockImagePickerTimerRef.current) {
        window.clearTimeout(unlockImagePickerTimerRef.current)
      }
    }
  }, [])

  function unlockImagePickerBlurGuard() {
    if (unlockImagePickerTimerRef.current) {
      window.clearTimeout(unlockImagePickerTimerRef.current)
    }
    unlockImagePickerTimerRef.current = window.setTimeout(() => {
      isOpeningImagePickerRef.current = false
      unlockImagePickerTimerRef.current = null
    }, 0)
  }

  const uploadFiles = React.useCallback(
    async (files: File[]) => {
      const images = files.filter((file) => file.type.startsWith("image/"))
      if (!images.length || imageUploading) {
        return
      }
      if (imageList.length >= COMMENT_IMAGE_LIMIT) {
        msgWarning(
          t("component.imageUpload.countLimitError", {
            limit: COMMENT_IMAGE_LIMIT,
          })
        )
        return
      }

      const remainingCount = COMMENT_IMAGE_LIMIT - imageList.length
      const uploadImages = images.slice(0, remainingCount)
      if (images.length > remainingCount) {
        msgWarning(
          t("component.imageUpload.countLimitError", {
            limit: COMMENT_IMAGE_LIMIT,
          })
        )
      }

      setShowImageUpload(true)
      setImageUploading(true)
      try {
        const uploaded: ImageInfo[] = []
        for (const file of uploadImages) {
          const result = await uploadImage(file)
          uploaded.push({ url: result.url })
        }
        onImageListChange([...(imageList || []), ...uploaded])
      } catch (error) {
        catchError(error)
      } finally {
        setImageUploading(false)
        textareaRef.current?.focus()
      }
    },
    [catchError, imageList, imageUploading, msgWarning, onImageListChange, t]
  )

  function openImagePicker() {
    setShowImageUpload(true)
    setIsFocus(true)
    textareaRef.current?.focus()
    if (!canAddImage) {
      msgWarning(
        t("component.imageUpload.countLimitError", {
          limit: COMMENT_IMAGE_LIMIT,
        })
      )
      return
    }
    isOpeningImagePickerRef.current = true
    window.addEventListener("focus", unlockImagePickerBlurGuard, { once: true })
    fileInputRef.current?.click()
  }

  function submit() {
    if (imageUploading) {
      msgWarning(t("component.textEditor.pleaseWait"))
      return
    }
    onSubmit()
  }

  function onPaste(event: React.ClipboardEvent<HTMLTextAreaElement>) {
    const files = Array.from(event.clipboardData.items)
      .filter((item) => item.type.startsWith("image/"))
      .map((item) => item.getAsFile())
      .filter((file): file is File => Boolean(file))

    if (!files.length) {
      return
    }

    event.preventDefault()
    void uploadFiles(files)
  }

  function onDrop(event: React.DragEvent<HTMLTextAreaElement>) {
    const files = Array.from(event.dataTransfer.files).filter((file) =>
      file.type.startsWith("image/")
    )
    if (!files.length) {
      return
    }

    event.preventDefault()
    event.stopPropagation()
    void uploadFiles(files)
  }

  function onBlur(event: React.FocusEvent<HTMLDivElement>) {
    const nextTarget = event.relatedTarget
    if (nextTarget && wrapperRef.current?.contains(nextTarget)) {
      return
    }
    if (isOpeningImagePickerRef.current) {
      return
    }
    setIsFocus(false)
    setShowImageUpload(false)
  }

  const dynamicHeight =
    isFocus && focusHeight > 0
      ? focusHeight + (showImageUpload ? 90 : 0)
      : height + (showImageUpload ? 90 : 0)

  return (
    <div
      ref={wrapperRef}
      className={cn(
        "flex flex-col rounded-lg border border-transparent bg-muted transition-all duration-200",
        focusHeight > 0 && "has-editor-focus",
        isFocus && "border-ring bg-background"
      )}
      style={{ height: dynamicHeight }}
      onBlur={onBlur}
    >
      <textarea
        ref={textareaRef}
        value={content}
        placeholder={t("component.textEditor.placeholder")}
        className={cn(
          "block w-full flex-1 resize-none rounded-t-lg border-0 bg-muted p-2.5 font-[inherit] leading-[1.8] text-foreground outline-0 overscroll-contain",
          isFocus && "bg-background"
        )}
        disabled={disabled}
        onFocus={() => {
          setIsFocus(true)
          if (currentImages.length) {
            setShowImageUpload(true)
          }
        }}
        onInput={(event) => {
          onContentChange(event.currentTarget.value)
          if (event.currentTarget.value) {
            setIsFocus(true)
          }
        }}
        onPaste={onPaste}
        onDrop={onDrop}
        onKeyDown={(event) => {
          if ((event.metaKey || event.ctrlKey) && event.key === "Enter") {
            event.preventDefault()
            submit()
          }
        }}
      />
      {showImageUpload ? (
        <div
          className="flex h-[90px] flex-wrap gap-2 overflow-auto p-2.5"
          onMouseDown={(event) => event.preventDefault()}
        >
          {currentImages.map((image, index) => (
            <div
              key={`${image.url || image.preview || index}`}
              className="group relative h-[60px] w-[60px] overflow-hidden rounded bg-background"
            >
              <PreviewableImage
                src={imageSrc(image)}
                previewSrcList={currentImages.map(imageSrc)}
                initialIndex={index}
                alt=""
                className="h-full w-full object-cover"
              />
              <button
                type="button"
                className="absolute top-1 right-1 hidden rounded bg-black/50 p-0.5 text-white group-hover:block"
                onClick={() =>
                  onImageListChange(
                    imageList.filter((_, imageIndex) => imageIndex !== index)
                  )
                }
              >
                <X className="h-3 w-3" />
              </button>
            </div>
          ))}
          {!imageUploading && canAddImage ? (
            <button
              type="button"
              className="flex h-[60px] w-[60px] items-center justify-center rounded border border-dashed border-border bg-background text-muted-foreground hover:border-primary hover:text-primary"
              onClick={openImagePicker}
            >
              <Plus className="h-5 w-5" />
            </button>
          ) : null}
          {imageUploading ? (
            <div className="flex h-[60px] min-w-[60px] items-center justify-center rounded bg-background px-2 text-xs text-muted-foreground">
              {t("component.imageUpload.uploading")}
            </div>
          ) : null}
        </div>
      ) : null}
      <div
        className={cn(
          "flex h-9 items-center justify-between rounded-b-lg bg-muted px-2.5 py-[3px]",
          isFocus && "bg-background"
        )}
      >
        <button
          type="button"
          className={cn(
            "flex cursor-pointer select-none items-center gap-1 text-muted-foreground hover:text-primary",
            showImageUpload && "font-medium text-primary"
          )}
          onClick={openImagePicker}
        >
          <ImageIcon className="h-5 w-5" />
        </button>
        <Button
          type="button"
          className="h-6"
          disabled={disabled}
          onClick={submit}
        >
          {t("component.textEditor.publish")}
        </Button>
        <input
          ref={fileInputRef}
          type="file"
          accept="image/*"
          multiple
          className="hidden"
          onChange={(event) => {
            unlockImagePickerBlurGuard()
            const files = Array.from(event.currentTarget.files || [])
            void uploadFiles(files)
            event.currentTarget.value = ""
          }}
        />
      </div>
    </div>
  )
})

// site/src/components/TextEditor.vue
<template>
  <div
    class="text-editor"
    :class="{ 'has-editor-focus': focusHeight > 0, 'is-focus': isFocus }"
    v-click-outside="onBlur"
  >
    <textarea
      ref="textarea"
      v-model="post.content"
      :placeholder="$t('component.textEditor.placeholder')"
      @paste="handleParse"
      @drop="handleDrag"
      @keydown.ctrl.enter="doSubmit"
      @keydown.meta.enter="doSubmit"
      @focus="onFocus"
      @input="onContentChange"
    />
    <div
      ref="imageUploaderContainer"
      v-show="showImageUpload"
      class="text-editor-image-uploader"
    >
      <image-upload
        ref="imageUploader"
        v-model="post.imageList"
        v-model:on-upload="imageUploading"
        size="60px"
      />
    </div>
    <div class="text-editor-bar">
      <div class="text-editor-actions">
        <div
          class="text-editor-action-item"
          :class="{ active: showImageUpload }"
          @click="switchImageUpload"
        >
          <i class="iconfont icon-image" />
        </div>
      </div>
      <div class="text-editor-btn">
        <button class="button is-primary" @click="doSubmit">
          {{ $t("component.textEditor.publish") }}
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
const { t } = useI18n();
const props = defineProps({
  height: {
    type: Number,
    default: 80,
  },
  focusHeight: {
    type: Number,
    default: 0,
  },
  content: {
    type: String,
    default: "",
  },
  imageList: {
    type: Array,
    default: () => [],
  },
});

const emit = defineEmits(["submit", "update:content", "update:imageList"]);

const post = ref({
  content: props.content,
  imageList: props.imageList,
});
const isFocus = ref(false);
const textarea = ref(null);
const showImageUpload = ref(false); // 是否显示图片上传
const imageUploader = ref(null);
const imageUploaderContainer = ref(null);
const imageUploading = ref(false); // 图片上传中
const dynamicHeight = ref(props.height);
const dynamicFocusHeight = ref(props.focusHeight);
const isUpdatingHeight = ref(false); // 防止递归更新的标志

watch(
  () => props.content,
  (newVal, oldVal) => {
    post.value.content = props.content;
  }
);

watch(
  () => props.imageList,
  (newVal, oldVal) => {
    post.value.imageList = props.imageList || [];
  }
);

watch(
  () => showImageUpload.value,
  (newVal, oldVal) => {
    if (!isUpdatingHeight.value) {
      updateHeight();
    }
  }
);

watch(
  () => post.value.content,
  (newVal, oldVal) => {
    emit("update:content", post.value.content);
  }
);

watch(
  () => post.value.imageList,
  (newVal, oldVal) => {
    emit("update:imageList", post.value.imageList);
  }
);

const doSubmit = () => {
  if (imageUploading.value === true) {
    useMsgWarning(t("component.textEditor.pleaseWait"));
    return;
  }
  emit("submit");
};

const handleParse = (e) => {
  const items = e.clipboardData && e.clipboardData.items;
  if (!items || !items.length) {
    return;
  }

  let file = null;
  for (let i = 0; i < items.length; i++) {
    if (items[i].type.includes("image")) {
      file = items[i].getAsFile();
    }
  }

  if (file) {
    e.preventDefault(); // 阻止默认行为即不让剪贴板内容显示出来
    showImageUpload.value = true; // 展开上传面板
    imageUploader.value.addFiles([file]);
    focus();
  }
};
const handleDrag = (e) => {
  e.stopPropagation();
  e.preventDefault();

  const items = e.dataTransfer.items;
  if (!items || !items.length) {
    return;
  }

  const files = [];
  for (let i = 0; i < items.length; i++) {
    if (items[i].type.includes("image")) {
      files.push(items[i].getAsFile());
    }
  }

  if (files && files.length) {
    showImageUpload.value = true; // 展开上传面板
    imageUploader.value.addFiles(files);
    focus();
  }
};
const switchImageUpload = () => {
  if (!showImageUpload.value) {
    // 打开文件弹窗
    imageUploader.value.onClick();
    focus();
  }
  showImageUpload.value = !showImageUpload.value;
};
const focus = () => {
  textarea.value.focus();
};
const onFocus = () => {
  isFocus.value = true;
  // 只有在图片列表存在且当前未显示上传区域时才展开
  if (
    post.value.imageList &&
    post.value.imageList.length &&
    !showImageUpload.value
  ) {
    showImageUpload.value = true;
  }
};
const onBlur = () => {
  isFocus.value = false;
  showImageUpload.value = false;
};
const reset = () => {
  isFocus.value = false;
  showImageUpload.value = false;
};
const updateHeight = () => {
  // 防止递归更新
  if (isUpdatingHeight.value) {
    return;
  }
  isUpdatingHeight.value = true;

  // 等dom变更完成后在计算高度，否则计算不准
  nextTick(() => {
    try {
      if (!imageUploaderContainer.value) {
        isUpdatingHeight.value = false;
        return;
      }
      const uploadHeight = imageUploaderContainer.value.offsetHeight || 0;
      if (showImageUpload.value) {
        dynamicHeight.value = props.height + uploadHeight;
        dynamicFocusHeight.value = props.focusHeight + uploadHeight;
      } else {
        dynamicHeight.value = props.height;
        dynamicFocusHeight.value = props.focusHeight;
      }
    } finally {
      // 使用 setTimeout 确保在下一个事件循环后重置标志
      setTimeout(() => {
        isUpdatingHeight.value = false;
      }, 0);
    }
  });
};

const onContentChange = () => {
  if (post.value.content) {
    isFocus.value = true;
  }
};

defineExpose({
  reset,
  focus,
});
</script>

<style lang="scss" scoped>
.text-editor {
  --text-editor-height: v-bind(dynamicHeight + "px");
  --text-editor-focus-height: v-bind(dynamicFocusHeight + "px");

  $bgColor: var(--bg-color3);
  $borderRadius: 8px;

  background: $bgColor;
  border-radius: $borderRadius;
  height: var(--text-editor-height);
  border: 1px solid transparent;

  display: flex;
  flex-direction: column;
  transition: all 200ms;

  &.is-focus {
    &.has-editor-focus {
      height: var(--text-editor-focus-height) !important;
    }

    border: 1px solid var(--border-hover-color);
    background: var(--bg-color) !important;
    textarea,
    .text-editor-bar {
      background: var(--bg-color) !important;
    }
  }

  textarea {
    background: $bgColor;
    border-top-left-radius: $borderRadius;
    border-top-right-radius: $borderRadius;
    height: calc(100% - 36px);
    width: 100%;
    font-family: inherit;
    border: 0;
    outline: 0;
    display: block;
    position: relative;
    resize: none;
    line-height: 1.8;
    padding: 10px;
    overflow: auto;
    overscroll-behavior: contain;
    color: var(--text-color);

    &::-webkit-scrollbar {
      width: 6px;
      height: 6px;
      border-radius: 3px;
      background-color: transparent;
    }
    &::-webkit-scrollbar-thumb {
      background-color: transparent;
      border-radius: 3px;
      border: 2px solid transparent;
    }
    &:hover::-webkit-scrollbar {
      background-color: #e4e4e5;
    }
    &:hover::-webkit-scrollbar-thumb {
      background-color: #c0bebc;
    }
  }

  .text-editor-image-uploader {
    padding: 10px;
  }

  .text-editor-bar {
    background: $bgColor;
    border-bottom-left-radius: $borderRadius;
    border-bottom-right-radius: $borderRadius;
    padding: 3px 10px;
    display: flex;
    align-items: center;
    justify-content: space-between;

    .text-editor-actions {
      .text-editor-action-item {
        cursor: pointer;
        color: var(--text-color3);
        user-select: none;
        display: flex;
        align-items: center;
        column-gap: 5px;

        i {
          font-size: 20px;
        }

        &:hover {
          color: var(--text-link-color);
        }

        &.active {
          color: var(--text-link-color);
          font-weight: 500;
        }
      }
    }
    .text-editor-btn {
      display: flex;
      align-items: center;
      span {
        font-size: 12px;
        color: var(--text-color3);
        margin-right: 5px;
      }
      button {
        font-size: 12px;
        padding: 3px 10px;
      }
    }
  }
}
</style>
